### ISSUE TITLE
Unable to add product to cart

### ISSUE THREAD

**Issue by danivijay** [danivijay/react-e-commerce#58]
```
{"errors":[{"message":"Unknown argument \"owner_user_id\" on field \"transaction\" of type \"Mutation\". Did you mean \"user_id\"?","locations":[{"line":2,"column":131}]},{"message":"Cannot query field \"owner_user_id\" on type \"Transaction\". Did you mean \"user_id\"?","locations":[{"line":9,"column":5}]}]}
```

**Comment by ashinpchandran** [comment]
A new column owner_user_id was added in the transaction model and product model and the products added earlier didn't have this attribute and that is why the error occurred. Now I have added a new product and then tried to add the same to the cart and it was successful.
